### ISSUE TITLE
Empty host

### ISSUE THREAD

**Issue by Giga-mox** [PhoenixFire6879/Classic-Brawl#67]
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 19, in <module>
  File "<string>", line 15, in main
  File "/storage/emulated/0/Classic-Brawl-2.0/Core/Networking/Server.py", line 18, in __init__
    self.db = MongoDB(self.config['MongoConnectionURL'])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/emulated/0/Classic-Brawl-2.0/DataBase/MongoDB.py", line 14, in __init__
    self.client = pymongo.MongoClient(conn_str, serverSelectionTimeoutMS = 5000)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py", line 797, in __init__
    seeds.update(uri_parser.split_hosts(entity, port))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/pymongo/uri_parser.py", line 392, in split_hosts
    raise ConfigurationError("Empty host (or extra comma in host list).")
pymongo.errors.ConfigurationError: Empty host (or extra comma in host list).

[Program finished]

How to fix?

**Comment by 8-bitHacc** [comment]
https://imgur.com/a/oXI34dA
Follow this tutorial ^^
(Note: MongoDB will not be required in near updates. so you will not experience this problem when Classic Brawl switches to another database)
